# Generated by Django 6.0.4 on 2026-05-13 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descriptions',
            new_name='description',
        ),
    ]
